### PR TITLE
fixes issues 195 and 192

### LINKED ISSUE #192: More bulletproof server meta validation
Randomly spotted while trying to track down why my CLI file uploading was failing...

Re: [/server/server.js:191-199](https://github.com/mozilla/send/blob/52173bf6e79c35fbba7e3493fae94ebf9d53b4c0/server/server.js#L191-L199), I think we're doing some things out of order here, since we're trying to validate the `meta.id` value before checking if the `meta` object has an 'id' property:

```js
  if (
    !validateIV(meta.id) ||
    !meta.hasOwnProperty('aad') ||
    !meta.hasOwnProperty('id') ||
    !meta.hasOwnProperty('filename')
  ) {
    res.sendStatus(404);
    return;
  }
```

### LINKED ISSUE #195: Investigate unicode filenames
Do we handle this already or not?

ref https://www.npmjs.com/package/content-disposition

### PR DESCRIPTION
**Pull request by abhinadduri**
Fixes #192 
Fixes #195

### CODE REVIEW

File: server/server.js [hunk 1]
```diff
@@ -189,10 +189,10 @@ app.post('/upload', (req, res, next) => {
   }
 
   if (
-    !validateIV(meta.id) ||
     !meta.hasOwnProperty('aad') ||
     !meta.hasOwnProperty('id') ||
-    !meta.hasOwnProperty('filename')
+    !meta.hasOwnProperty('filename' ||
```
Comment (pdehaan) [inline server/server.js]: I think... this is wrong.

```
!meta.hasOwnProperty('filename') ||
!validateIV(meta.id)
```

Comment (abhinadduri) [inline server/server.js]: Oops, nice catch! Messed up some indenting and ended up with that.

File: frontend/src/download.js [hunk 2]
```diff
@@ -65,7 +65,7 @@ $(document).ready(function() {
         return;
       })
       .then(([decrypted, fname]) => {
-        name.innerText = fname;
+        name.innerText = decodeURIComponent(fname);
```
Comment (abhinadduri) [inline frontend/src/download.js]: Yeah, will do.
