### PR TITLE
a few changes to make A/B testing easier

### LINKED ISSUE #376: l20n.min.js and upload.js not loading on `npm run`
I tried running this instance locally and I get a nonfunctional site. The console log message is 
> " The resource from “http://10.35.3.63:1443/l20n.min.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

>" The resource from “http://10.35.3.63:1443/upload.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

I am hoping my platform could not be the cause of this issue, I'm running:

```
npm     4.4.4
FreeBSD 10.3
```

I installed with:

```bash
git clone https://github.com/mozilla/send
cd send;
npm install --production
npm run
```

Output is:
```
~/send [master] » ls
Dockerfile         circle.yml         frontend           package.json       server             views
LICENSE            docker-compose.yml l10n.toml          public             static
README.md          docs               package-lock.json  scripts            test


~/send [master] » cat Docker
cat: Docker: No such file or directory


~/send [master] » cat Dockerfile 
FROM node:8-alpine

RUN apk add --no-cache git
RUN addgroup -S -g 10001 app && adduser -S -D -G app -u 10001 app
COPY . /app
RUN chown -R app /app
USER app
WORKDIR /app
RUN mkdir static
RUN npm install --production && npm cache clean --force

ENV PORT=1443
EXPOSE $PORT

CMD ["npm", "start"]
~/send [master] » npm install --production
firefox-send@1.0.2 /usr/home/jharasym/send
├─┬ aws-sdk@2.93.0 
│ ├─┬ buffer@4.9.1 
│ │ ├── base64-js@1.2.1 
│ │ ├── ieee754@1.1.8 
│ │ └── isarray@1.0.0 
│ ├── crypto-browserify@1.0.9 
│ ├── events@1.1.1 
│ ├── jmespath@0.15.0 
│ ├── querystring@0.2.0 
│ ├── sax@1.2.1 
│ ├─┬ url@0.10.3 
│ │ ├── punycode@1.3.2 
│ │ └── querystring@0.2.0  deduped
│ ├── uuid@3.0.1 
│ ├─┬ xml2js@0.4.17 
│ │ ├── sax@1.2.1  deduped
│ │ └── xmlbuilder@4.2.1  deduped
│ └─┬ xmlbuilder@4.2.1 
│   └── lodash@4.17.4 
├─┬ body-parser@1.17.2 
│ ├── bytes@2.4.0 
│ ├── content-type@1.0.2 
│ ├─┬ debug@2.6.7 
│ │ └── ms@2.0.0 
│ ├── depd@1.1.1 
│ ├─┬ http-errors@1.6.1 
│ │ ├── depd@1.1.0 
│ │ ├── inherits@2.0.3 
│ │ ├── setprototypeof@1.0.3  deduped
│ │ └── statuses@1.3.1  deduped
│ ├── iconv-lite@0.4.15 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── qs@6.4.0 
│ ├─┬ raw-body@2.2.0 
│ │ ├── bytes@2.4.0 
│ │ ├── iconv-lite@0.4.15  deduped
│ │ └── unpipe@1.0.0 
│ └─┬ type-is@1.6.15 
│   ├── media-typer@0.3.0 
│   └─┬ mime-types@2.1.16 
│     └── mime-db@1.29.0 
├── bytes@2.5.0 
├─┬ connect-busboy@0.0.2 
│ └─┬ busboy@0.2.14 
│   ├─┬ dicer@0.2.5 
│   │ ├── readable-stream@1.1.14  deduped
│   │ └── streamsearch@0.1.2 
│   └─┬ readable-stream@1.1.14 
│     ├── core-util-is@1.0.2 
│     ├── inherits@2.0.3  deduped
│     ├── isarray@0.0.1 
│     └── string_decoder@0.10.31 
├─┬ convict@3.0.0 
│ ├── depd@1.1.0 
│ ├── json5@0.5.1 
│ ├── lodash.clonedeep@4.5.0 
│ ├── minimist@1.2.0 
│ ├── moment@2.17.1 
│ ├── validator@7.0.0 
│ └─┬ varify@0.2.0 
│   ├─┬ redeyed@1.0.1 
│   │ └── esprima@3.0.0 
│   └── through@2.3.8 
├─┬ express@4.15.3 
│ ├─┬ accepts@1.3.3 
│ │ ├── mime-types@2.1.16  deduped
│ │ └── negotiator@0.6.1 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.2 
│ ├── content-type@1.0.2  deduped
│ ├── cookie@0.3.1 
│ ├── cookie-signature@1.0.6 
│ ├── debug@2.6.7  deduped
│ ├── depd@1.1.1  deduped
│ ├── encodeurl@1.0.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.8.0 
│ ├─┬ finalhandler@1.0.3 
│ │ ├── debug@2.6.7  deduped
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├── on-finished@2.3.0  deduped
│ │ ├── parseurl@1.3.1  deduped
│ │ ├── statuses@1.3.1  deduped
│ │ └── unpipe@1.0.0  deduped
│ ├── fresh@0.5.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├── on-finished@2.3.0  deduped
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.1.5 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.4.0 
│ ├── qs@6.4.0  deduped
│ ├── range-parser@1.2.0 
│ ├─┬ send@0.15.3 
│ │ ├── debug@2.6.7  deduped
│ │ ├── depd@1.1.1  deduped
│ │ ├── destroy@1.0.4 
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├── etag@1.8.0  deduped
│ │ ├── fresh@0.5.0  deduped
│ │ ├── http-errors@1.6.1  deduped
│ │ ├── mime@1.3.4 
│ │ ├── ms@2.0.0  deduped
│ │ ├── on-finished@2.3.0  deduped
│ │ ├── range-parser@1.2.0  deduped
│ │ └── statuses@1.3.1  deduped
│ ├─┬ serve-static@1.12.3 
│ │ ├── encodeurl@1.0.1  deduped
│ │ ├── escape-html@1.0.3  deduped
│ │ ├── parseurl@1.3.1  deduped
│ │ └── send@0.15.3  deduped
│ ├── setprototypeof@1.0.3 
│ ├── statuses@1.3.1 
│ ├── type-is@1.6.15  deduped
│ ├── utils-merge@1.0.0 
│ └── vary@1.1.1 
├─┬ express-handlebars@3.0.0 
│ ├─┬ glob@6.0.4 
│ │ ├─┬ inflight@1.0.6 
│ │ │ ├── once@1.4.0  deduped
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.3  deduped
│ │ ├─┬ minimatch@3.0.4 
│ │ │ └─┬ brace-expansion@1.1.8 
│ │ │   ├── balanced-match@1.0.0 
│ │ │   └── concat-map@0.0.1 
│ │ ├─┬ once@1.4.0 
│ │ │ └── wrappy@1.0.2  deduped
│ │ └── path-is-absolute@1.0.1 
│ ├── graceful-fs@4.1.11 
│ ├─┬ handlebars@4.0.10 
│ │ ├── async@1.5.2 
│ │ ├─┬ optimist@0.6.1 
│ │ │ ├── minimist@0.0.10 
│ │ │ └── wordwrap@0.0.3 
│ │ ├─┬ source-map@0.4.4 
│ │ │ └── amdefine@1.0.1 
│ │ └─┬ uglify-js@2.8.29 
│ │   ├── source-map@0.5.6 
│ │   ├── uglify-to-browserify@1.0.2 
│ │   └─┬ yargs@3.10.0 
│ │     ├── camelcase@1.2.1 
│ │     ├─┬ cliui@2.1.0 
│ │     │ ├─┬ center-align@0.1.3 
│ │     │ │ ├─┬ align-text@0.1.4 
│ │     │ │ │ ├─┬ kind-of@3.2.2 
│ │     │ │ │ │ └── is-buffer@1.1.5 
│ │     │ │ │ ├── longest@1.0.1 
│ │     │ │ │ └── repeat-string@1.6.1 
│ │     │ │ └── lazy-cache@1.0.4 
│ │     │ ├─┬ right-align@0.1.3 
│ │     │ │ └── align-text@0.1.4  deduped
│ │     │ └── wordwrap@0.0.2 
│ │     ├── decamelize@1.2.0 
│ │     └── window-size@0.1.0 
│ ├─┬ object.assign@4.0.4 
│ │ ├─┬ define-properties@1.1.2 
│ │ │ ├── foreach@2.0.5 
│ │ │ └── object-keys@1.0.11  deduped
│ │ ├── function-bind@1.1.0 
│ │ └── object-keys@1.0.11 
│ └─┬ promise@7.3.1 
│   └── asap@2.0.6 
├─┬ helmet@3.8.1 
│ ├─┬ connect@3.6.2 
│ │ ├── debug@2.6.7  deduped
│ │ ├── finalhandler@1.0.3  deduped
│ │ ├── parseurl@1.3.1  deduped
│ │ └── utils-merge@1.0.0  deduped
│ ├── dns-prefetch-control@0.1.0 
│ ├── dont-sniff-mimetype@1.0.0 
│ ├── expect-ct@0.1.0 
│ ├── frameguard@3.0.0 
│ ├─┬ helmet-csp@2.5.1 
│ │ ├── camelize@1.0.0 
│ │ ├─┬ content-security-policy-builder@1.1.0 
│ │ │ └── dashify@0.2.2 
│ │ ├── dasherize@2.0.0 
│ │ ├── lodash.reduce@4.6.0 
│ │ └── platform@1.3.4 
│ ├── hide-powered-by@1.0.0 
│ ├── hpkp@2.0.0 
│ ├── hsts@2.1.0 
│ ├── ienoopen@1.0.0 
│ ├── nocache@2.0.0 
│ ├── referrer-policy@1.1.0 
│ └── x-xss-protection@1.0.0 
├─┬ mozlog@2.1.1 
│ ├─┬ intel@1.2.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├─┬ strip-ansi@3.0.1 
│ │ │ │ └── ansi-regex@2.1.1  deduped
│ │ │ └── supports-color@2.0.0 
│ │ ├── dbug@0.4.2 
│ │ ├── stack-trace@0.0.10 
│ │ ├── strftime@0.10.0 
│ │ ├── symbol@0.3.1 
│ │ └── utcstring@0.1.0 
│ └── merge@1.2.0 
├─┬ raven@2.1.1 
│ ├── cookie@0.3.1  deduped
│ ├── json-stringify-safe@5.0.1 
│ ├── lsmod@1.0.0 
│ ├── stack-trace@0.0.9 
│ ├── timed-out@4.0.1 
│ └── uuid@3.0.0 
└─┬ redis@2.7.1 
  ├── double-ended-queue@2.1.0-0 
  ├── redis-commands@1.3.1 
  └── redis-parser@2.6.0 

~/send [master] » npm start

> firefox-send@1.0.2 start /usr/home/jharasym/send
> node server/server

FirefoxSend.send.server.INFO: startServer: Send app listening on port 1443!
^C
```

### LINKED ISSUE #441: Bad value “true” for attribute “hidden” on element “div”
via #139 

```
line 75   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 93   col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
line 106  col 1   Error  Bad value “true” for attribute “hidden” on element “div”.                                                                                                 html-checker
```

When fixing this, also make sure you search for Boolean instances of `.attr("hidden", ...)` in [/frontend/src/*.js](https://github.com/mozilla/send/tree/master/frontend/src) since we toggle the `hidden` attribute using jQuery as well. ❤️

### LINKED ISSUE #476: On Microsoft Edge the filename has strange placeholder characters "FSI"/"PDI"
[Affected versions]:
- Microsfot Edge

[Affected Platforms]:
- Windows 10

[Steps to reproduce]:
1. Start the Firefox browser and navigate to "https://send.stage.mozaws.net" page.
2. Drag and Drop a file in the Drop area.
3. Observe the file name text.

[Expected result]:
- The file name is correctly displayed.

[Actual results]:
- The filename has strange placeholder characters FSI/PDI surrounding them

[Notes]:
- Here is a screen shot with the issue:
edge

### LINKED ISSUE #509: Move server API routes to /api/ path?
Ref: https://github.com/mozilla/send/pull/506#issuecomment-321876187

> We should only render the `notfound` page for HTML endpoints; some of the 404s are API endpoints and will not be expecting a `notfound` HTML page.

Not sure if we should rename some API routes in [server/server.js](https://github.com/mozilla/send/blob/master/server/server.js) so all API routes are under some /api/ prefixed path so they are a bit more obvious.

### Proposal:

| CURRENT | PROPOSED |
|:----|:----|
| `app.get('/exists/:id', ...)` | `app.get('/api/exists/:id', ...)`
| `app.get('/assets/download/:id', ...)` | `app.get('/api/download/:id', ...)`
| `app.post('/delete/:id', ...)` | `app.post('/api/delete/:id', ...)`
| `app.post('/upload', ...)` | `app.post('/api/upload', ...)`

But I don't think this would apply to the following routes:

- `app.get('/')`
- `app.get('/unsupported/:reason')`
- `app.get('/legal')`
- `app.get('/jsconfig.js')`
- `app.get('/download/:id')`
- `app.get('/__lbheartbeat__')`
- `app.get('/__heartbeat__')`
- `app.get('/__version__')`

### LINKED ISSUE #532: Move `<script>` tags into bottom of `<body>`
Per https://github.com/mozilla/send/pull/516#discussion_r133370602

@pdehaan says:

> _Do these 3 `<script>` tags need to be in the `<head>`, or can we move them to the end of the `<body>` tag? In my very unscientific testing, this had a decent sized performance improvement when testing locally using Lighthouse, but that isn't always a great measure._

@dannycoates replies:

> _They shouldn't need to be in the head. worth a shot_

### PR DESCRIPTION
**Pull request by dannycoates**
also,

fixes #532 
fixes #509 
fixes #476 
fixes #441
fixes #376

### CODE REVIEW

File: app/routes/index.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+app.route('/', require('./home'));
+app.route('/share/:id', require('../templates/share'));
+app.route('/download/:id', download);
+app.route('/download/:id/:key', download);
+app.route('/completed', require('../templates/completed'));
+app.route('/unsupported/:reason', require('../templates/unsupported'));
+app.route('/legal', require('../templates/legal'));
+app.route('/error', require('../templates/error'));
+app.route('/blank', require('../templates/blank'));
+app.route('*', require('../templates/notFound'));
```
Comment (pdehaan) [inline app/routes/index.js]: I haven't tested this locally yet, but... don't we need the `/__version__` route, as well as the two health check OPs routes?

File: app/routes/index.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
+const choo = require('choo');
+const download = require('./download');
```
Comment (pdehaan) [inline app/routes/index.js]: nit: Is it weird that /app/storage.js uses `import * from blah` syntax but these other files use `require('baz')`?

File: app/templates/file.js [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+const assets = require('../../common/assets');
+
+function timeLeft(milliseconds) {
+  const minutes = Math.floor(milliseconds / 1000 / 60);
+  const hours = Math.floor(minutes / 60);
+  const seconds = Math.floor(milliseconds / 1000 % 60);
+  if (hours >= 1) {
+    return `${hours}h ${minutes % 60}m`;
+  } else if (hours === 0) {
+    return `${minutes}m ${seconds}s`;
```
Comment (pdehaan) [inline app/templates/file.js]: Cant remember if we have a bug or TODO for making these localize-able...

File: app/templates/file.js [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+      <div class="popup">
+        <div class="popuptext" onclick=${stopProp} onblur=${cancel} tabindex="-1">
+          <div class="popup-message">${state.translate('deletePopupText')}</div>
+          <div class="popup-action">
+            <span class="popup-no" onclick=${cancel}>${state.translate(
+    'deletePopupCancel'
+  )}</span>
+            <span class="popup-yes" onclick=${deleteFile}>${state.translate(
+    'deletePopupYes'
+  )}</span>
```
Comment (pdehaan) [inline app/templates/file.js]: Some of these indents look pretty wack. Not sure if that is a prettier bug or some other subtle edge.

File: app/templates/fileList.js [hunk 5]
```diff
@@ -0,0 +1,29 @@
+const html = require('choo/html');
+const file = require('./file');
+
+module.exports = function(state, emit) {
+  const table = html`
+  <table id="uploaded-files">
+    <thead>
+      <tr>
+        <!-- htmllint attr-bans="false" -->
```
Comment (pdehaan) [inline app/templates/fileList.js]: nit: We don't use htmllint anymore, and can kill these comments. Sorry.

File: app/templates/fileList.js [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+        <th id="delete-file-list">${state.translate('deleteFileList')}</th>
+        <!-- htmllint tag-bans="$previous" -->
+      </tr>
+    </thead>
+    <tbody>
+      ${state.storage.files.map(f => file(f, state, emit))}
+    </tbody>
+  </table>
+  `;
+  const list = state.storage.files.length ? table : '';
```
Comment (pdehaan) [inline app/templates/fileList.js]: Should we check `state.storage.files.length` sooner and just abort early if there are no files? May save some l20n lookups and templating, etc.

File: app/templates/share.js [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+
+  async function copyLink() {
+    if (allowedCopy()) {
+      emit('copy', { url: file.url, location: 'success-screen' });
+      const copyBtn = document.getElementById('copy-btn');
+      copyBtn.disabled = true;
+      copyBtn.replaceChild(
+        html`<img src="${assets.get(
+          'check-16.svg'
+        )}" class="icon-check"></img>`,
```
Comment (pdehaan) [inline app/templates/share.js]: I know this was just copy/pasta, but we can just use a shorthand `class="icon-check" />`. Seeing an `</img>` feels like all sorts of wrong.

File: app/utils.js [hunk 8]
```diff
@@ -35,47 +35,39 @@ function notify(str) {
   */
 }
 
-function gcmCompliant() {
+function loadShim(polyfill) {
+  return new Promise((resolve, reject) => {
+    const shim = document.createElement('script');
+    shim.src = polyfill;
+    shim.addEventListener('load', () => resolve(true));
+    shim.addEventListener('error', () => resolve(false));
```
Comment (pdehaan) [inline app/utils.js]: I can't remember how these are being used, but should we be doing `resolve(false)` or just rejecting the promise?

File: app/routes/index.js (hunk 1 above)
Comment (dannycoates) [reply app/routes/index.js]: These are routes relative to the frontend js app. Server-only routes are in `server/routes/index.js`

File: app/routes/index.js (hunk 2 above)
Comment (dannycoates) [reply app/routes/index.js]: It is weird. In order to run this code on the server, for server rendering, without transpiling some of it has to stick with require style. That being the case we might want to just go with node style require everywhere.

File: app/templates/file.js (hunk 4 above)
Comment (dannycoates) [reply app/templates/file.js]: I'm not a fan of the line breaks either

File: app/utils.js (hunk 8 above)
Comment (dannycoates) [reply app/utils.js]: It's just a design choice. I'd rather return a boolean than use a try/catch block on the await.

File: app/templates/file.js (hunk 3 above)
Comment (dannycoates) [reply app/templates/file.js]: do now #538

File: app/templates/completed.js [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+const progress = require('./progress');
+const { fadeOut } = require('../utils');
+
+module.exports = function(state, emit) {
+  const div = html`
+  <div id="download" class="fadeIn">
+    <div id="download-progress">
+      <div id="dl-title" class="title">${state.translate(
+        'downloadFinish'
+      )}</div>
```
Comment (pdehaan) [inline app/templates/completed.js]: I'm a bit confused on what the difference between `state.translate('blah')` and just setting a `data-l10n-id="baz"` attribute and let l20n handle translations.

Comment (dannycoates) [reply app/templates/completed.js]: The l20n lib is gone. We don't want two different libs both making changes to the same dom nodes. And bonus, this lets us do l10n on the server as well.

Comment (pdehaan) [reply app/templates/completed.js]: ah, OK... in that case, we might have 2 lingering references to `data-l10n-id`:

```sh
$ git grep data-l10n-id

app/templates/error.js:    <img id="upload-error-img" data-l10n-id="errorAltText" src="${assets.get(
app/templates/notFound.js:        )}" id="expired-img" data-l10n-id="linkExpiredAlt"/>
```

File: server/routes/index.js [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+  app.get('/legal', pages.legal);
+  app.get('/jsconfig.js', require('./jsconfig'));
+  app.get('/share/:id', pages.blank);
+  app.get('/download/:id', pages.download);
+  app.get('/completed', pages.blank);
+  app.get('/unsupported/:reason', pages.unsupported);
+  app.post('/api/upload', require('./upload'));
+  app.get('/api/download/:id', require('./download'));
+  app.get('/api/exists/:id', require('./exists'));
+  app.post('/api/delete/:id', require('./delete'));
```
Comment (ehuggett) [inline server/routes/index.js]: should this change have incremented the version number? (or if not, could it do so in the future?) I'm not presuming `/__version__` will always be available, but i was hoping to use it for the time being as a sanity check https://github.com/ehuggett/send-cli/issues/1

Comment (dannycoates) [reply server/routes/index.js]: The version number will change when we tag a release. For the master branch we might want to add a label to the version.json version to indicate that it may not be stable, for example "v1.1.2-master.53e822", meaning the release version will be some semver > 1.1.2. Would that help your situation?

Comment (ehuggett) [reply server/routes/index.js]: > The version number will change when we tag a release.

Its only just dawning on me how foolish attempting to support send.dev.mozaws.net by checking the version number is 🤣 Sorry! (I can't even claim i was half asleep)

It would make the check simpler, but I will check the value of commit AND version to determine this ie if (version == "v1.1.2" && commit == "0bf8481") {ok stable} else {warn about unstable} .
https://send.dev.mozaws.net/__version__ 
`{"commit":"ced640c","source":"https://github.com/mozilla/send/","version":"v1.1.2"}`

Which will also work if someone uses the --service-local or --service <url> for dev usage, and might still work on versions >1.1.2 if they are similar enough, so thanks for the suggestion, but I didn't realise i already had everything i needed to attempt "reliable" behaviour.
