### PR TITLE
fixed issues in branch title

### LINKED ISSUE #152: Better validation of query params
Ref: #151

I don't have a lot of experience with this in Express (it's much easier in Hapi), but we may want to look at some parameter validation using Express middleware using something like [**express-validator**](https://github.com/ctavan/express-validator).

We validate the `req.params.id` parameter in some places, but not others.

| METHOD | ROUTE | VALIDATED |
|----|----|----|
| **GET** | ['/exists/:id'](https://github.com/mozilla/something-awesome/blob/a7fcb1a44f26bd567e2555249e776c027048f357/server/portal_server.js#L45) | No. :-1:
| **GET** | ['/download/:id'](https://github.com/mozilla/something-awesome/blob/a7fcb1a44f26bd567e2555249e776c027048f357/server/portal_server.js#L55) | No. 👎 
| **GET** | ['/assets/download/:id'](https://github.com/mozilla/something-awesome/blob/a7fcb1a44f26bd567e2555249e776c027048f357/server/portal_server.js#L74) | Yes. 🌈 
| **POST** | ['/delete/:id'](https://github.com/mozilla/something-awesome/blob/a7fcb1a44f26bd567e2555249e776c027048f357/server/portal_server.js#L113) | Yes. 🦄 
| **POST** | ['/upload/:id'](https://github.com/mozilla/something-awesome/blob/a7fcb1a44f26bd567e2555249e776c027048f357/server/portal_server.js#L138) | Yes. 🎉

### LINKED ISSUE #158: Redirect to 404 page is not performed if you click the "Download" button after file has expired
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://fileshare.dev.mozaws.net/" page.
2. Upload a file and open the download link in two different tabs.
3. Download the file in the first tab and then navigate to the second tab.
4. Click the download button and observe the behavior.

[Expected result]:
- The page is refreshed and the "Link expired" page is displayed.

[Actual results]:
- Nothing happens.

[Notes]:
- This issue is also reproducible on the stage page (https://fileshare.stage.mozaws.net). 
- If the page is manually refreshed, the "Link expired" page is correctly displayed.
- Here is a screen recording with the issue:
404 page not displayed after clicking on the download button

### PR DESCRIPTION
**Pull request by abhinadduri**
FIxes #152 
Fixes #158

### CODE REVIEW

File: server/portal_server.js [hunk 1]
```diff
@@ -101,10 +111,14 @@ app.get('/assets/download/:id', (req, res) => {
             })
             .catch(err => {
               log.info('DeleteError:', id);
+              res.sendStatus(404);
```
Comment (dannycoates) [inline server/portal_server.js]: This will not work. The response has already been sent. Let's talk about what we can do when a delete fails
